# # ベースイメージの指定
# FROM openjdk:17

# # 作業ディレクトリの設定
# WORKDIR /app

# # JARファイルをコンテナにコピー
# COPY target/wikimedia-producer-0.0.1-SNAPSHOT.jar /app/wikimedia-producer.jar

# # アプリケーションの実行
# ENTRYPOINT ["java", "-jar", "/app/wikimedia-producer.jar"]



